import dotenv from "dotenv";
import { Api } from "grammy";
dotenv.config({ path: ".env.local" });
const required = ["BOT_TOKEN", "APP_URL", "MINI_APP_URL"] as const;
for (const name of required) if (!process.env[name]) throw new Error(`${name} is not defined`);
const appUrl = process.env.APP_URL!.replace(/\/$/, "");
const api = new Api(process.env.BOT_TOKEN!);
await api.setWebhook(`${appUrl}/api/telegram`);
await api.setChatMenuButton({ menu_button: { type: "web_app", text: "Приложение ✨", web_app: { url: process.env.MINI_APP_URL! } } });
console.info("Webhook and Menu Button are configured.");
