import assert from "node:assert/strict";
import { tariffs, mockVideos } from "../src/bot/mock/data";
import { tariffsKeyboard } from "../src/bot/keyboards/balance";
import { videoListKeyboard } from "../src/bot/keyboards/videos";
import { mainKeyboard } from "../src/bot/keyboards/main";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { composePrompt } from "../src/lib/prompt";
import { defaultMontageSettings } from "../src/montage/types";
import { verifyTelegramInitData } from "../src/lib/auth";
import { closeDatabase, createProject, failProject, getUser, hasActiveProject, reserveGeneration, updateProject } from "../src/lib/database";
assert.ok(mockVideos.length > 0, "At least one mock video is required");
assert.equal(videoListKeyboard(mockVideos).inline_keyboard.length, mockVideos.length);
assert.equal(tariffsKeyboard(tariffs).inline_keyboard.length, tariffs.length + 1);
assert.ok(tariffs.every((tariff) => tariff.tokens > 0 && tariff.priceRubles > 0));
const buttonStyle = (row: number, column: number) => {
  const button = mainKeyboard.keyboard[row][column];
  return typeof button === "string" || !("style" in button) ? undefined : button.style;
};
assert.equal(buttonStyle(0, 0), "primary");
assert.equal(buttonStyle(1, 0), "success");
assert.equal(buttonStyle(1, 1), "primary");
const prompt = composePrompt({ ...defaultMontageSettings, color: "crimson", generateHook: true, badges: true });
assert.ok(prompt.includes("crimson-red"));
assert.ok(prompt.includes("compelling visual hook"));
assert.ok(prompt.includes("glass badges"));
assert.ok(!prompt.includes("sound design"));
assert.ok(prompt.indexOf("Glass Reels") < prompt.indexOf("crimson-red"));
assert.ok(prompt.indexOf("crimson-red") < prompt.indexOf("compelling visual hook"));
const token = "verification-token";
const init = new URLSearchParams({ auth_date: String(Math.floor(Date.now() / 1000)), query_id: "test", user: JSON.stringify({ id: 42, first_name: "Test" }) });
const check = [...init.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `${key}=${value}`).join("\n");
const secret = crypto.createHmac("sha256", "WebAppData").update(token).digest();
init.set("hash", crypto.createHmac("sha256", secret).update(check).digest("hex"));
assert.equal(verifyTelegramInitData(init.toString(), token).id, "42");
init.set("user", JSON.stringify({ id: 99 }));
assert.throws(() => verifyTelegramInitData(init.toString(), token));
const verificationDb = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "aibot-verify-")), "app.sqlite");
process.env.DATABASE_PATH = verificationDb;
process.env.TELEGRAM_ALLOWED_USER_IDS = "42";
process.env.APP_URL = "http://verification.local";
process.env.BOT_TOKEN = "verification-token";
process.env.SESSION_SECRET = "verification-session-secret";
assert.equal(getUser("42").balance, 100);
const project = createProject("verify-project", "42", defaultMontageSettings);
assert.ok(hasActiveProject("42"));
updateProject(project.id, { status: "uploaded", inputPath: "/tmp/input.mp4" });
assert.equal(reserveGeneration(project.id, "42", prompt).ok, true);
assert.equal(getUser("42").balance, 77);
failProject(project.id, "provider_failed");
assert.equal(getUser("42").balance, 100);
closeDatabase();
fs.rmSync(path.dirname(verificationDb), { recursive: true, force: true });
console.info("Keyboards, prompt ordering, Telegram initData and mock token reservation passed.");
